program = [ variable ]
          { "function" ident "{" statement "}" }
          "main "{" statement "}"

program = { statement }

statement = [ variable
            | call ident
            | "if" condition "{" statement "}"
            | "loop" condition "{" statement "}" ]
            | for i in 1..N do "{" statement "}" // Maybe add this niciety.

variable = "let" identifier = expression

identifier = character { character | digit }

expression = factor
           | condition
           | 

factor = [ "+" | "-" ] term { ( "+" | "-") term }

condition = ( "true" | "false" )

character = (A-Z)
          | (a-z)

digit = [0-9] { [0-9] }

number = a { [+|-] a }

a = b { [*|/] b }

b = "(" number ")"
  | number
  | digit