
program = variable(;variable)*

variable = let <identifier> = <expression>

expression = character(character)*
           | num(num)*

character = (A-Z)
          | (a-z)



number = factor { [+|-] factor }

factor = number { [*|/] number }
       | [0-9]
